-- Função auxiliar para policies de admin sem causar recursão nas policies da tabela profiles.
create or replace function public.is_admin(check_user uuid default auth.uid())
returns boolean
language sql
security definer
set search_path = public
as $$
  select coalesce((select p.is_admin from public.profiles p where p.id = check_user), false);
$$;

-- Coluna opcional para foto de perfil.
-- A imagem é salva como texto/base64 para evitar configuração extra de Storage.
alter table public.profiles add column if not exists foto_url text;

-- Tabelas para o módulo Minha Biblioteca / Metas de Leitura
-- Execute este arquivo no SQL Editor do Supabase.

create table if not exists public.biblioteca_usuario (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  titulo text not null,
  autor text,
  total_paginas int not null check (total_paginas > 0),
  pagina_atual int not null default 0 check (pagina_atual >= 0),
  status text not null default 'quero_ler' check (status in ('quero_ler', 'lendo', 'lido')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  concluido_em timestamptz
);

create table if not exists public.metas_leitura (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  meta_diaria_paginas int not null default 20 check (meta_diaria_paginas > 0),
  meta_mensal_livros int not null default 1 check (meta_mensal_livros > 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.registros_leitura (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  biblioteca_id bigint not null references public.biblioteca_usuario(id) on delete cascade,
  paginas_lidas int not null check (paginas_lidas > 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_biblioteca_usuario_user_id on public.biblioteca_usuario(user_id);
create index if not exists idx_biblioteca_usuario_status on public.biblioteca_usuario(status);
create index if not exists idx_metas_leitura_user_id on public.metas_leitura(user_id);
create index if not exists idx_registros_leitura_user_id on public.registros_leitura(user_id);
create index if not exists idx_registros_leitura_data on public.registros_leitura(created_at);

alter table public.biblioteca_usuario enable row level security;
alter table public.metas_leitura enable row level security;
alter table public.registros_leitura enable row level security;

-- Políticas: cada usuário acessa apenas os próprios dados de leitura.
drop policy if exists "biblioteca_select_own" on public.biblioteca_usuario;
drop policy if exists "biblioteca_insert_own" on public.biblioteca_usuario;
drop policy if exists "biblioteca_update_own" on public.biblioteca_usuario;
drop policy if exists "biblioteca_delete_own" on public.biblioteca_usuario;

create policy "biblioteca_select_own" on public.biblioteca_usuario
for select using (auth.uid() = user_id);

create policy "biblioteca_insert_own" on public.biblioteca_usuario
for insert with check (auth.uid() = user_id);

create policy "biblioteca_update_own" on public.biblioteca_usuario
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "biblioteca_delete_own" on public.biblioteca_usuario
for delete using (auth.uid() = user_id);

drop policy if exists "metas_select_own" on public.metas_leitura;
drop policy if exists "metas_insert_own" on public.metas_leitura;
drop policy if exists "metas_update_own" on public.metas_leitura;
drop policy if exists "metas_delete_own" on public.metas_leitura;

create policy "metas_select_own" on public.metas_leitura
for select using (auth.uid() = user_id);

create policy "metas_insert_own" on public.metas_leitura
for insert with check (auth.uid() = user_id);

create policy "metas_update_own" on public.metas_leitura
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "metas_delete_own" on public.metas_leitura
for delete using (auth.uid() = user_id);

drop policy if exists "registros_select_own" on public.registros_leitura;
drop policy if exists "registros_insert_own" on public.registros_leitura;
drop policy if exists "registros_update_own" on public.registros_leitura;
drop policy if exists "registros_delete_own" on public.registros_leitura;

create policy "registros_select_own" on public.registros_leitura
for select using (auth.uid() = user_id);

create policy "registros_insert_own" on public.registros_leitura
for insert with check (auth.uid() = user_id);

create policy "registros_update_own" on public.registros_leitura
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "registros_delete_own" on public.registros_leitura
for delete using (auth.uid() = user_id);


-- Campos para deixar os anúncios mais próximos de um marketplace real.
-- fotos: guarda até algumas imagens em JSON/Base64 ou URLs.
-- estado: registra a conservação do livro.
alter table public.livros add column if not exists fotos jsonb not null default '[]'::jsonb;
alter table public.livros add column if not exists estado text not null default 'usado_bom';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'livros_estado_check'
  ) then
    alter table public.livros
    add constraint livros_estado_check
    check (estado in ('novo', 'seminovo', 'usado_bom', 'usado_marcado', 'danificado'));
  end if;
end $$;


-- Avaliações e comentários dos livros/anúncios.
-- Cada usuário pode avaliar o mesmo anúncio uma vez; se avaliar novamente, o sistema atualiza a avaliação.
create table if not exists public.avaliacoes_livros (
  id bigint generated by default as identity primary key,
  livro_id bigint not null references public.livros(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  nota int not null check (nota between 1 and 5),
  comentario text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_avaliacoes_livros_livro_id on public.avaliacoes_livros(livro_id);
create index if not exists idx_avaliacoes_livros_user_id on public.avaliacoes_livros(user_id);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'avaliacoes_livros_livro_user_unique'
  ) then
    alter table public.avaliacoes_livros
    add constraint avaliacoes_livros_livro_user_unique unique (livro_id, user_id);
  end if;
end $$;

alter table public.avaliacoes_livros enable row level security;

drop policy if exists "avaliacoes_select_auth" on public.avaliacoes_livros;
drop policy if exists "avaliacoes_insert_own" on public.avaliacoes_livros;
drop policy if exists "avaliacoes_update_own" on public.avaliacoes_livros;
drop policy if exists "avaliacoes_delete_own_or_admin" on public.avaliacoes_livros;

create policy "avaliacoes_select_auth" on public.avaliacoes_livros
for select using (auth.uid() is not null);

create policy "avaliacoes_insert_own" on public.avaliacoes_livros
for insert with check (auth.uid() = user_id);

create policy "avaliacoes_update_own" on public.avaliacoes_livros
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "avaliacoes_delete_own_or_admin" on public.avaliacoes_livros
for delete using (
  auth.uid() = user_id
  or public.is_admin()
);


-- Pedidos/interesses de compra.
-- Esta tabela deixa a função de compra mais organizada: o pedido fica registrado e também gera conversa no chat.
create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  comprador_id uuid not null references public.profiles(id) on delete cascade,
  vendedor_id uuid not null references public.profiles(id) on delete cascade,
  livro_id bigint references public.livros(id) on delete set null,
  status text not null default 'aberto' check (status in ('aberto', 'em_negociacao', 'concluido', 'cancelado')),
  valor numeric(10,2) not null default 0,
  forma_entrega text default 'combinar',
  observacao text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_pedidos_comprador on public.pedidos(comprador_id);
create index if not exists idx_pedidos_vendedor on public.pedidos(vendedor_id);
create index if not exists idx_pedidos_livro on public.pedidos(livro_id);
create index if not exists idx_pedidos_status on public.pedidos(status);

alter table public.pedidos enable row level security;

drop policy if exists "pedidos_select_own_or_admin" on public.pedidos;
drop policy if exists "pedidos_insert_buyer" on public.pedidos;
drop policy if exists "pedidos_update_own_or_admin" on public.pedidos;
drop policy if exists "pedidos_delete_admin" on public.pedidos;

create policy "pedidos_select_own_or_admin" on public.pedidos
for select using (
  auth.uid() = comprador_id
  or auth.uid() = vendedor_id
  or public.is_admin()
);

create policy "pedidos_insert_buyer" on public.pedidos
for insert with check (auth.uid() = comprador_id);

create policy "pedidos_update_own_or_admin" on public.pedidos
for update using (
  auth.uid() = comprador_id
  or auth.uid() = vendedor_id
  or public.is_admin()
) with check (
  auth.uid() = comprador_id
  or auth.uid() = vendedor_id
  or public.is_admin()
);

create policy "pedidos_delete_admin" on public.pedidos
for delete using (
  public.is_admin()
);

-- Políticas adicionais para o painel admin conseguir gerenciar dados pelo cliente autenticado.
-- Observação: apagar o usuário do Supabase Auth continua exigindo ação pelo painel do Supabase ou backend com Service Role.
drop policy if exists "profiles_admin_select_all" on public.profiles;
drop policy if exists "profiles_admin_delete_non_admin" on public.profiles;

create policy "profiles_admin_select_all" on public.profiles
for select using (
  auth.uid() = id
  or public.is_admin()
);

create policy "profiles_admin_delete_non_admin" on public.profiles
for delete using (
  id <> auth.uid()
  and coalesce(is_admin, false) = false
  and public.is_admin()
);

drop policy if exists "livros_admin_all" on public.livros;
create policy "livros_admin_all" on public.livros
for all using (
  dono = auth.uid()
  or public.is_admin()
) with check (
  dono = auth.uid()
  or public.is_admin()
);

drop policy if exists "mensagens_admin_all" on public.mensagens;
create policy "mensagens_admin_all" on public.mensagens
for all using (
  sender_id = auth.uid()
  or receiver_id = auth.uid()
  or public.is_admin()
) with check (
  sender_id = auth.uid()
  or receiver_id = auth.uid()
  or public.is_admin()
);

drop policy if exists "biblioteca_admin_all" on public.biblioteca_usuario;
create policy "biblioteca_admin_all" on public.biblioteca_usuario
for all using (
  user_id = auth.uid()
  or public.is_admin()
) with check (
  user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists "metas_admin_all" on public.metas_leitura;
create policy "metas_admin_all" on public.metas_leitura
for all using (
  user_id = auth.uid()
  or public.is_admin()
) with check (
  user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists "registros_admin_all" on public.registros_leitura;
create policy "registros_admin_all" on public.registros_leitura
for all using (
  user_id = auth.uid()
  or public.is_admin()
) with check (
  user_id = auth.uid()
  or public.is_admin()
);
